USGS-Astrogeology/ISIS3

- isis/src/base/objs/Process/unitTest.xml
- isis/src/base/objs/SpectralDefinition2D/unitTest.cpp
- isis/src/base/objs/SubArea/unitTest.xml
- isis/src/mro/objs/HiLab/unitTest.cpp
Fixed unit test cube locations for SpectralDefinition2D, Process, SubArea, HiLab
> Updated unit tests cube locations for remaining objects

- isis/src/base/objs/LinearAlgebra/LinearAlgebra.cpp
- isis/src/base/objs/LinearAlgebra/LinearAlgebra.h
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.h
Adding first draft of versioned control points.
> Adding versioned control points and the create methods for them.

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.h
The actual construction of the control points is not in here because the control points are not defined yet. The v0007 read also needs to be added once we make a v0007 proto file.
> First implementation of read methods in ControlNetVersioner

- .gitignore
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.h
I did branching incorrectly and wiped out my own toPvl changes. Here I'm adding them back. Also re-added the .gitignore so git status is more useful again.
> Re-added toPvl and gitignore

- .gitignore
We version the .proto files, not the generated code so we should add the generated code to out git ignore file
> Added protobuf generated code to git ignore

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.h
Merging Write() fixes (from PR29) back into the ControlNetVersioner_Write branch
> Modified ControlNetVersioner to reflect PR#29 comments appropriately.

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.h
- isis/src/control/objs/ControlPoint/ControlPoint.cpp
- isis/src/control/objs/ControlPoint/ControlPoint.h
Also added IsJigsawRejecte to ControlPoint.
> Fixed some method names in ControlNetVersioner. 

- isis/src/control/objs/ControlNetVersioner/ControlPointV0001.cpp
- isis/src/control/objs/ControlNetVersioner/ControlPointV0001.h
- isis/src/control/objs/ControlNetVersioner/ControlPointV0002.cpp
- isis/src/control/objs/ControlNetVersioner/ControlPointV0002.h
- isis/src/control/objs/ControlNetVersioner/ControlPointV0003.cpp
- isis/src/control/objs/ControlNetVersioner/ControlPointV0003.h
> Fixed several errors in versioned control point classes

- isis/src/control/objs/ControlPoint/ControlPoint.cpp
Fixed ControlPoint.cpp so that it compiles.
> Fixed ControlPoint so that it compiles.

- isis/src/base/objs/ProcessImportPds/ProcessImportPds.cpp
- isis/src/base/objs/ProcessImportPds/ProcessImportPds.h
Modified error message in ProcessImportPds::ProcessLabel() to be more descriptive. Fixes #4883
> Modified error message for ProcessImportPds

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
Implemented conditional statements to ensure values exist before attempting to read/write them.
> Added conditionals to ensure values exist before reading/writing them.

- isis/src/control/objs/ControlMeasure/ControlMeasure.h
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
Fixed references in ControlNetVersioner to those accessors.
> Removed references to invalid accessor methods in ControlMeasure.

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
There were two issues with the attempting to calculate sigmas in meters without radii and a problem with how the ControlMeasure log data was being accessed.
> Fixed issues with ControlNet unitTest and ControlNetVersioner

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
Also fixed inconsistent header data (where the header would always display 0 pts 0 measures).
> Fixed "Missing Required Fields" for Protobuf Control Points

- isis/src/control/objs/ControlMeasure/unitTest.cpp
Also added a newline between the end of test 13 and the start of test 14.
> Removed commented out accessors in ControlMeasure unit test

- isis/src/control/objs/.ControlNetStatistics-tst.stderr.log
- isis/src/control/objs/.ControlNetStatistics-tst.stdout.log
- isis/src/control/objs/ControlMeasure/ControlMeasure.h
- isis/src/control/objs/ControlNet/ControlNet.h
- isis/src/control/objs/ControlNetDiff/ControlNetDiff.h
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.h
- isis/src/control/objs/ControlNetVersioner/ControlPointV0001.cpp
- isis/src/control/objs/ControlNetVersioner/ControlPointV0001.h
- isis/src/control/objs/ControlNetVersioner/ControlPointV0002.cpp
- isis/src/control/objs/ControlNetVersioner/ControlPointV0002.h
- isis/src/control/objs/ControlNetVersioner/ControlPointV0003.cpp
- isis/src/control/objs/ControlNetVersioner/ControlPointV0003.h
Also improved documentation of code added to other classes in the refactor.
> Improved ControlNetVersioner documentation

- isis/src/control/objs/ControlMeasure/ControlMeasure.cpp
- isis/src/control/objs/ControlMeasure/ControlMeasure.h
Moved sample / line initialization from constructor to InitToNull() method
> Updated initialization in ControlMeasure

- isis/src/control/objs/ControlNetDiff/cnet.pvl
- isis/src/control/objs/ControlNetDiff/cnet2.pvl
- isis/src/control/objs/ControlNetVersioner/ControlPointV0001.cpp
And fixed some ControlNetDiff test data I'd modified incorrectly earlier.
> Update ControlPointV0001 in to read in actual v1 pvls

- isis/src/control/objs/ControlMeasureLogData/ControlMeasureLogData.h
Also, fixed a previous history comment I made that I inaccurately logged as being from 2012.
> Added variable names to method declarations in ControlMeasureLogData.

- isis/src/control/objs/ControlNetVersioner/ControlPointV0001.cpp
These were required for old test data to pass.
> Added AprioriXYZSouceFile and AprioriXYZSource to ControlPointV0001

- isis/src/base/apps/isisminer/CnetReaderStrategy.cpp
There are a lot of changes because the old code had a ton of trailing spaces
> Changed isisminer to use new ControlNetVersioner

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.truth
- isis/src/control/objs/ControlNetVersioner/unitTest.cpp
Updated the ControlNetVersioner truth data.
> Updated versioner truth data

- isis/src/control/objs/ControlMeasure/ControlMeasure.truth
- isis/src/control/objs/ControlMeasure/unitTest.cpp
Added unit tests for HasChooserName() and HasDateTime()
> Updated ControlMeasure truth data

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
Updated toPvl() to call ApioriSurfacePoint::SetRadii() before accessing the lat/long sigma values in meters.
> Updated ControlNetVersioner::toPvl()

- isis/src/qisis/objs/AdvancedTrackTool/AdvancedTrackTool.cpp
- isis/src/qisis/objs/AdvancedTrackTool/AdvancedTrackTool.h
tModified AdvancedTrackTool to call showTable() before it attempts to record a point so that a table is created and the first recorded point is displayed in the table.
> Updated AdvancedTrackTool to show first point recorded.

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
Also modified the adjusted covariance matrix to only display if there's valid values in it.
> Updated Versioner to omit blank/null choosername/datetime

- isis/src/base/objs/Gui/Gui.cpp
- isis/src/base/objs/Gui/Gui.h
Reverts USGS-Astrogeology/ISIS3#104
> Revert "Addressed memory leak in Gui.cpp involving X-forwarding. Fixes #4736"

- isis/src/control/objs/ControlNet/ControlNet.truth
(See title.) I'm going for the shortest pull request ever.
> Updated ControlNet truthdata to have version = 5

- isis/src/base/objs/ProcessImportPds/ProcessImportPds.cpp
- isis/src/base/objs/ProcessImportPds/ProcessImportPds.h
- isis/src/base/objs/PvlToPvlTranslationManager/PvlToPvlTranslationManager.cpp
- isis/src/base/objs/PvlToPvlTranslationManager/PvlToPvlTranslationManager.h
- isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp
- isis/src/kaguya/apps/mimap2isis/mimap2isis.cpp
- isis/src/voyager/apps/voy2isis/voy2isis.cpp
- isis/src/voyager/apps/voy2isis/voy2isis.xml
Reverts USGS-Astrogeology/ISIS3#119
> Revert "Changed voy2isis to allow for ingestion of IMG/LBL pairs and Pds Archive images. Fixes #4345, #4421."

- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.h
Changed how ControlPoint radii are set upon initialization in ControlNetVersioner.
> Updated how ControlPoint radii are set.

- isis/src/base/objs/Histogram/Histogram.truth
- isis/src/control/apps/cnethist/tsts/case01/Makefile
- isis/src/control/objs/ControlNet/ControlNet.cpp
- isis/src/control/objs/ControlNet/ControlNet.h
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.cpp
- isis/src/control/objs/ControlNetVersioner/ControlNetVersioner.h
Updated cnethist makefile to ignore new Progress output for respective changes.
> Added Progress support to ControlNetVersioner and ControlNet

- isis/src/base/objs/ProcessImportPds/ProcessImportPds.cpp
- isis/src/base/objs/ProcessImportPds/ProcessImportPds.h
- isis/src/base/objs/PvlToPvlTranslationManager/PvlToPvlTranslationManager.cpp
- isis/src/base/objs/PvlToPvlTranslationManager/PvlToPvlTranslationManager.h
- isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp
- isis/src/kaguya/apps/mimap2isis/mimap2isis.cpp
- isis/src/voyager/apps/voy2isis/voy2isis.cpp
- isis/src/voyager/apps/voy2isis/voy2isis.xml
Reverts USGS-Astrogeology/ISIS3#127
> Revert "Changes voy2isis to allow for ingestion of IMG/LBL pairs and Pds Archive images"

- isis/src/base/objs/ProcessImportPds/ProcessImportPds.cpp
- isis/src/base/objs/ProcessImportPds/ProcessImportPds.h
- isis/src/base/objs/PvlToPvlTranslationManager/PvlToPvlTranslationManager.cpp
- isis/src/base/objs/PvlToPvlTranslationManager/PvlToPvlTranslationManager.h
- isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp
- isis/src/kaguya/apps/mimap2isis/mimap2isis.cpp
- isis/src/voyager/apps/voy2isis/voy2isis.cpp
- isis/src/voyager/apps/voy2isis/voy2isis.xml
Reverts USGS-Astrogeology/ISIS3#126
> Revert "Revert "Changed voy2isis to allow for ingestion of IMG/LBL pairs and Pds Archive images. Fixes #4345, #4421.""

- isis/src/base/objs/Gui/Gui.cpp
- isis/src/base/objs/Gui/Gui.h
Reverts USGS-Astrogeology/ISIS3#120
> Revert "Updated handling of memory leak in Gui.cpp to fix pull request. Refer…"

- isis/src/base/objs/Gui/Gui.cpp
- isis/src/base/objs/Gui/Gui.h
Reverts USGS-Astrogeology/ISIS3#118
> Revert "Revert "Addressed memory leak in Gui.cpp involving X-forwarding. Fixes #4736""

- isis/src/qisis/objs/WindowTool/WindowTool.cpp
- isis/src/qisis/objs/WindowTool/WindowTool.h
Reverts USGS-Astrogeology/ISIS3#115
> Revert "Fixed fullscreen tilling issue Fixes #5262"

- isis/src/base/objs/Cube/Cube.cpp
- isis/src/base/objs/Cube/Cube.h
- isis/src/base/objs/Cube/Cube.truth
Reverts USGS-Astrogeology/ISIS3#112
> Revert "Updated error message is Cube::create() to address when IsisPreferenc..."

- isis/src/docsys/documents/InstallGuide/InstallGuide.xml
Reverts USGS-Astrogeology/ISIS3#111
> Revert "Updated InstallGuide to include newer missions and to give better war…"

- isis/src/control/apps/cnethist/tsts/case01/Makefile
> Removed debug statement in ControlNetVersioner.

- isis/src/base/objs/ProcessImportPds/ProcessImportPds.cpp
- isis/src/base/objs/ProcessImportPds/ProcessImportPds.h
- isis/src/base/objs/PvlToPvlTranslationManager/PvlToPvlTranslationManager.cpp
- isis/src/base/objs/PvlToPvlTranslationManager/PvlToPvlTranslationManager.h
- isis/src/base/objs/PvlTranslationTable/PvlTranslationTable.cpp
- isis/src/kaguya/apps/mimap2isis/mimap2isis.cpp
- isis/src/voyager/apps/voy2isis/voy2isis.cpp
- isis/src/voyager/apps/voy2isis/voy2isis.xml
Reverts USGS-Astrogeology/ISIS3#142
> Revert "Revert "Revert "Changed voy2isis to allow for ingestion of IMG/LBL pairs and Pds Archive images. Fixes #4345, #4421."""

- isis/src/base/objs/Gui/Gui.cpp
- isis/src/base/objs/Gui/Gui.h
- isis/src/control/objs/ControlMeasure/ControlMeasure.cpp
- isis/src/control/objs/ControlNet/ControlNet.cpp
- isis/src/control/objs/ControlNet/ControlNet.h
- isis/src/control/objs/ControlNetDiff/ControlNetDiff.cpp
- isis/src/control/objs/ControlNetFilter/ControlNetFilter.cpp
- isis/src/control/objs/ControlNetFilter/ControlNetFilter.h
- isis/src/control/objs/ControlNetStatistics/ControlNetStatistics.cpp
- isis/src/control/objs/ControlNetStatistics/ControlNetStatistics.h
- isis/src/control/objs/ControlNetValidMeasure/ControlNetValidMeasure.cpp
- isis/src/control/objs/ControlPoint/ControlPoint.cpp
- isis/src/control/objs/ControlPointList/ControlPointList.h
- isis/src/qisis/objs/AdvancedTrackTool/AdvancedTrackTool.cpp
- isis/src/qisis/objs/AdvancedTrackTool/AdvancedTrackTool.h
- isis/src/qisis/objs/FeatureNomenclature/FeatureNomenclature.cpp
- isis/src/qisis/objs/FeatureNomenclature/FeatureNomenclature.h
- isis/src/qisis/objs/MatchTool/MatchTool.cpp
- isis/src/qisis/objs/MatchTool/MatchTool.h
Builds and passes tests on Fedora 25.
This is in preparation for the merge back into dev.
> Merge of dev into ControlNetVersioner refactor branch

- isis/src/qisis/objs/WindowTool/WindowTool.cpp
- isis/src/qisis/objs/WindowTool/WindowTool.h
Reverts USGS-Astrogeology/ISIS3#145
> Revert "Revert "Fixed fullscreen tilling issue Fixes #5262""

- isis/src/base/apps/automos/automos.xml
This was edited before white space package was disabled code changes are at  
Lines:
473-476
812-814
829-831
> Updated automos xml to check for max min conflicts Fixes #5148
